Added most popular articles
manishpathak3173/NYTimesiOSApp pull request #1
Opened 2020-11-23 06:35 UTC by manishpathak3173

2020-11-30 07:56 UTC, serveshwar requested changes
Please add PR description. An ideal PR description should contain below items,
- Brief description of impact of changes that has been committed in the PR.
- UI Screenshots.
- Unit test case coverage report.
- Better to attach Sonarcube report.

Default ulitilities like JsonDecoder, Storyboard can be followed instead of writing custom boiler points codes.

Unit test case can be more exhaustive.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/Entity/PopularModel.swift
> +        copyright <- map["copyright"]
I understand that since you are using `AlamofireObjectMapper` hence all this mapping is required in data model as it implements `Mappable` protocol.

But its always better to use JsonDecoder provided by Apple by default as it overcomes below mentioned major drawbacks of `AlamofireObjectMapper`,
1. Provide hardcoded mapping for each property of the model.
2. Code becomes very large and more error prone as hardcoded keys from the map need to be mapped.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/Interactor/PopularListInteractor.swift
> +        remoteDatamanager?.retrieveArticleList()
`fromOffset` is not being used in the function.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/Protocols/PopularListProtocol.swift
> +    func setLoadingState(_ loading: Bool)
All these function can be modularised to another base presenter protocol, as it would make it more scalable and suffice the requirement of being used in other presenters as well in future.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +    override func awakeFromNib() {
This can be removed as no functionality is added here apart from base implementation.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +    static func reuseId() -> String {
Since all the UI classes will be subclass of `UIResponder` hence instead of hardcoding reuseId in each class, we can create an extension of UIResponder and use it.

`extension UIResponder {
    static var identifier: String {
        return "\(self)"
    }
}`

Instead of calling `ArticlesTableViewCell.reuseId` we can directly call ArticlesTableViewCell.identifier` wherever required.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +//        if let media = articles[indexPath.row].media, media.count > 0 {
Please remove commented code.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +        let updated = articles[indexPath.row].updated!
Force unwrapping can lead to crash, hence it should be avoided.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
Date formats can be placed in constant file.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +    var tableView: UITableView!
Please mark these as private (set) if not being set from outside.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        }
Is there a specific reason that you are not using storyboard?
All of these boiler point codes can be managed from storyboard.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        let filterNib = UINib(nibName: "ArticlesTableViewCell", bundle: nil)
`UIResponder.identifier` can be used as explained in earlier comment instead of hard-coded name.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +            self.articles.removeAll()
Since instance variables are by default referenced with self hence specifically mentioning self can be avoided.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +
Empty implementation?

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        return UITableView.automaticDimension
Not required can be directly configured while setting table view.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +                cell.layoutIfNeeded()
Avoid calling these functions until or unless very much required, as it will slow down the rendering of table view.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesAppTests/MostPopular/View/ArticleListViewControllerTests.swift
> +extension PopularListViewController {
Please have it in difference stub file.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesAppTests/MostPopular/View/Cell/ArticleCellTests.swift
> +//
No test case.

2020-11-30 07:56 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        activityView.style = .whiteLarge
'whiteLarge' was deprecated in iOS 13.0: renamed to 'UIActivityIndicatorView.Style.large'

2020-12-01 14:58 UTC, manishpathak3173 commented on NYTimesApp/Common/Endpoints.swift
> +            case .fetch: return "/svc/mostpopular/v2/viewed/7.json?api-key=Nwmkx1WuqAEsJX65G33zAOfLFNAhGFHQ"
Done.

2020-12-01 15:03 UTC, manishpathak3173 commented on NYTimesApp/DataManager/Remote/ArticleListRemoteDataManager.swift
> +        print(endpointWithParam)
Removed print statement , Its not required.

2020-12-01 15:03 UTC, manishpathak3173 commented on NYTimesApp/Extension/Results.swift
> +//  Results.swift
Done.

2020-12-01 15:09 UTC, manishpathak3173 commented on NYTimesApp/Extension/UIAlertViewController.swift
> +        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
Done.

2020-12-01 15:13 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/Interactor/PopularListInteractor.swift
> +        remoteDatamanager?.retrieveArticleList()
Removed as its not required .

2020-12-03 06:48 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +    static func reuseId() -> String {
Done

2020-12-03 06:48 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +//        if let media = articles[indexPath.row].media, media.count > 0 {
Done

2020-12-03 10:14 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
done

2020-12-03 10:27 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +    var tableView: UITableView!
For testing we are calling from ArticleListViewControllerSpec file for testing case .

2020-12-03 11:07 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        }
Yeah but as project grows , the views became more complex and needed to accommodate various screen sizes, the hierarchy of constraints became more and more difficult to tie down. For this I've used snapkit. Its very cool :)

2020-12-03 11:07 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        let filterNib = UINib(nibName: "ArticlesTableViewCell", bundle: nil)
Done

2020-12-03 11:08 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        return UITableView.automaticDimension
Removed.

2020-12-03 11:35 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/Protocols/PopularListProtocol.swift
> +    func setLoadingState(_ loading: Bool)
Separated in another protocols . Done.

2020-12-03 11:36 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +    override func awakeFromNib() {
Done.

2020-12-03 11:47 UTC, manishpathak3173 commented on NYTimesApp/DataManager/Remote/ArticleListRemoteDataManager.swift
> +                self.isAPICallInProgress = false
Done.

2020-12-03 11:47 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +
Done.

2020-12-03 11:48 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        activityView.style = .whiteLarge
Done.

2020-12-03 11:53 UTC, manishpathak3173 commented on NYTimesAppTests/MostPopular/View/ArticleListViewControllerTests.swift
> +extension PopularListViewController {
Done.

2020-12-03 11:53 UTC, manishpathak3173 commented on NYTimesAppTests/MostPopular/View/Cell/ArticleCellTests.swift
> +//
Unnecessary so I removed it.

2020-12-06 15:50 UTC, serveshwar commented on NYTimesApp/MostPopular/Entity/PopularModel.swift
> +        copyright <- map["copyright"]
Please update on this, as this comment is not incorporated in latest code.

2020-12-06 16:34 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        }
Good to know this, however as per the coding guideline here, we maximize the use of iOS default frameworks and methodologies. Hence, please either use storyboard or SwiftUI.

2020-12-06 16:47 UTC, serveshwar commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +            self.articles.removeAll()
Please update on this, as comment is not incorporated in latest code base.

2020-12-07 11:26 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +            self.articles.removeAll()
Done.

2020-12-07 16:38 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/PopularListViewController.swift
> +        }
Done

2020-12-07 16:38 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/Entity/PopularModel.swift
> +        copyright <- map["copyright"]
Done

2020-12-07 16:39 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/View/Cell/ArticlesTableViewCell.swift
> +        let updated = articles[indexPath.row].updated!
Done

2020-12-07 18:07 UTC, serveshwar commented on NYTimesApp/Extension/UIAlertViewController.swift
> +        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
preferredStyle parameter is not being used, instead .alert is still being used.

2020-12-07 18:14 UTC, serveshwar commented on NYTimesApp/MostPopular/Entity/PopularModel.swift
> +        copyright <- map["copyright"]
Good to see JsonDecoder being used now, however code can be cleaned more,
1. `init(from decoder: Decoder) throws` is not required, as its default behavior of JsonDecoder, until we need to do any specific thing in init method.
2. Model contains so many properties which are not being used. It is unnecessarily increasing memory.

2020-12-07 18:47 UTC, serveshwar commented
Most of the review comments as per PR #1 has been resolved. There 3 new comments based on new changes implemented,
Please check 

- https://github.com/manishpathak3173/NYTimesiOSApp/pull/1#discussion_r537721670
- https://github.com/manishpathak3173/NYTimesiOSApp/pull/1#discussion_r537717284
- Unit tests are not compiling because of the changes.

There are some warnings still present. Please check and resolve them.
<img width="262" alt="Screen Shot 2020-12-07 at 22 34 13" src="https://user-images.githubusercontent.com/46758783/101390632-95ac7500-38dc-11eb-87c7-eded51923f64.png">

We can merge this PR, once above points are resolved.

2020-12-08 05:07 UTC, manishpathak3173 commented on NYTimesApp/MostPopular/Entity/PopularModel.swift
> +        copyright <- map["copyright"]
Removed unnecessary fields.

2020-12-08 05:16 UTC, manishpathak3173 commented on NYTimesApp/Extension/UIAlertViewController.swift
> +        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
Done. 

Using both as parameterised. 
1- UIAlertController.Style. 
2- UIAlertAction.Style

2020-12-08 17:58 UTC, serveshwar commented
Unit Tests are compiling now, but the coverage is still 72.4% of NYTimesApp target. To get this result, you need to edit the NYTimesApp scheme and under info in Test tab add NYTimesAppTests.

90.48% is the coverage for test case classes i.e. NYTimesAppTests target.

2020-12-09 10:23 UTC, merged